=== KerinR432/PaginasWebs/introducción-xml/agenda.dtd
<!ELEMENT agenda (persona+)>
<!ELEMENT persona (nombre,apellido,apellido?,(movil|fijo)*,jubilado?)>
<!ELEMENT nombre (#PCDATA)>  <!-- es #PCDATA para aquello que su almacenamineto acaba-->
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT fijo (#PCDATA)>
<!ELEMENT jubilado EMPTY> <!-- ELEMENTO VACIO-->

<!ATTLIST persona 
sexo (varon|mujer|otro|nscn) "nscn" 
profesion CDATA #IMPLIED
> <!-- DEFINIMOS UN ATTLIST PARA LOS ELEMENTOS QUE TENGA MAS DE UN ATRIBUTO, PERO SOLO ELLOOS!!!!-->
<!-- REQUIRED="Obligatorio" IMPLIED="No obligatorio" FIXED="Un valor siempre fijo"-->
<!ATTLIST movil 
compa침ia CDATA #FIXED "vodafone"
tipo (contrato|prepago) #REQUIRED 
>
<!-- EMPTY es para un elemento que no tenga contenido-->
<!-- ?= 0 칩 1, * = 0 칩 n , += 1 칩 n-->
<!-- ID = valor unico de tipo identifiacador, IDREF = el valor de ese atributo es un elemento ID que aparezca en otro sitio en el mismo elemento-->
<!-- IDREFS = Es una lista de referencias unicas que debe aprecer en xml-->

=== KerinR432/PaginasWebs/introducción-xml/xml/Introducción.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
	<persona sexo="mujer" profesion="funcionaria">
		<nombre>Ana</nombre>
		<apellido>Garcia</apellido>
        <movil compaÃ±ia="vodafone" tipo="prepago" >321323123</movil>
        <fijo>854539857</fijo>
	</persona>
	<persona profesion="personal de compaÃ±ia" sexo="varon">
		<nombre>Freddy</nombre>
		<apellido>Bernabue</apellido>
        <fijo>499348382</fijo>
	</persona>
	<persona>
		<nombre>Mark</nombre>
		<apellido>Ruiz</apellido>
		<jubilado/>
	</persona>
</agenda>
