=== KerinR432/PaginasWebs/introducción-xml/arbol.dtd
<!ELEMENT arbol (persona*)>
<!ELEMENT persona (nombre,apellido,apellido,esposo?,esposa?,hijos*,padres?,fecha_nacimiento,fecha_defuncion?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT esposo (#PCDATA)>
<!ELEMENT esposa (#PCDATA)>
<!ELEMENT hijos (#PCDATA)>
<!ELEMENT padres (padre?,madre?)>
<!ELEMENT padre (#PCDATA)>
<!ELEMENT madre (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT fecha_defuncion (#PCDATA)>

=== KerinR432/PaginasWebs/introducción-xml/arbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arbol SYSTEM "arbol.dtd">
<arbol>
    <persona>
        <nombre>Pepe</nombre>
        <apellido>Gonzales</apellido>
        <apellido>Goya</apellido>
        <esposa>Gimena Perez</esposa>
        <hijos>Frederico</hijos>
        <hijos>Francisco</hijos>
        <hijos>Patrica</hijos>
        <padres>
            <padre>Juan</padre>
            <madre>Maria</madre>
        </padres>
        <fecha_nacimiento>21-3-1989</fecha_nacimiento>
    </persona>
    <persona>
        <nombre>Marsela</nombre>
        <apellido>Galve</apellido>
        <apellido>Higaldo</apellido>
        <esposo>Marcos Gimenez</esposo>
        <esposa>Sara Bentarcut</esposa>
        <padres>
            <padre>Carlos</padre>
            <madre>Carlotta</madre>
        </padres>
        <fecha_nacimiento>21-3-1989</fecha_nacimiento>
        <fecha_defuncion>4-12-2015</fecha_defuncion>
    </persona>

</arbol>
