=== KerinR432/PaginasWebs/introducción-xml/colecion.dtd
<!ELEMENT colecion (album*)>
<!ELEMENT album (titulo,autor,autor?,año,soporte,grabacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT soporte (#PCDATA)>
<!ELEMENT grabacion (#PCDATA)>

=== KerinR432/PaginasWebs/introducción-xml/colecion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colecion SYSTEM "colecion.dtd">
<colecion>
<album>
    <titulo>Copilotos</titulo>
    <autor>Arde Bogota</autor>
    <a単o>2023</a単o>
    <soporte>Spotify</soporte>
    <grabacion>Estudio</grabacion>
</album>
<album>
    <titulo>Marcha Turca</titulo>
    <autor>Bettoven</autor>
    <autor>Morzart</autor>
    <a単o>1760</a単o>
    <soporte>Vinilo</soporte>
    <grabacion>directo</grabacion>
</album>

</colecion>
