=== KerinR432/PaginasWebs/introducción-xml/ejercicio2.dtd
<!ELEMENT biblioteca (usuarios?,libros*)>
<!ELEMENT usuarios (usuario+)>
<!ELEMENT usuario (nombre)>
<!ATTLIST usuario
id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo,autor*)>
<!ATTLIST libro
id ID #REQUIRED
formato (epub|pdf|mobi) #FIXED "epub"
estado (disponible|prestado|reservado) #IMPLIED
prestadoA  IDREF #IMPLIED
reservadoA  IDREFS #IMPLIED 
>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

=== KerinR432/PaginasWebs/introducción-xml/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "ejercicio2.dtd">
<biblioteca>
    <usuarios>
        <usuario id="u001">
            <nombre>Ana Pérez</nombre>
        </usuario>
        <usuario id="u002">
            <nombre>Carlos Ruiz</nombre>
        </usuario>
    </usuarios>
    <libros>
        <libro id="b001" formato="epub" estado="disponible">
            <titulo>Cien Años de Soledad</titulo>
            <autor>Gabriel García Márquez</autor>
        </libro>
        <libro id="b002" estado="prestado" prestadoA="u001">
            <titulo>1984</titulo>
            <autor>George Orwell</autor>
        </libro>
        <libro id="b003" estado="reservado" reservadoA="u002">
            <titulo>El Principito</titulo>
            <autor>Antoine de Saint-Exupéry</autor>
        </libro>
    </libros>
</biblioteca>
