=== KerinR432/PaginasWebs/introducción-xml/liga.dtd
<!ELEMENT liga (partido*)>
<!ELEMENT partido (equipo*,tarjeta,colegiado,juez+)>
<!ELEMENT equipo (nombreEq,goles?)>
<!ELEMENT nombreEq (#PCDATA)>
<!ELEMENT goles (cantidad,nombre*)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tarjeta (jugador*)>
<!ELEMENT jugador (#PCDATA)>
<!ELEMENT colegiado (#PCDATA)>
<!ELEMENT juez (#PCDATA)>
<!ATTLIST equipo
id (visitante|local) #REQUIRED  

>
<!ATTLIST jugador 
card (amarillo|rojo) #IMPLIED
>

=== KerinR432/PaginasWebs/introducción-xml/liga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "liga.dtd">
<liga>
    <partido>
        <equipo id = "local">
            <nombreEq>Chapitas</nombreEq>
            <goles>
                <cantidad>2</cantidad>
                <nombre>Franker</nombre>
                <nombre>Mister Palomino</nombre>
            </goles>
        </equipo>

        <equipo id = "visitante">
            <nombreEq>los paluminos</nombreEq>
        </equipo>
        <tarjeta>
            <jugador card = "amarillo">mika</jugador>
            <jugador card = "rojo">sasr</jugador>
        </tarjeta>
        <colegiado>Mikel</colegiado>
        <juez>Marques</juez>
        <juez>Mauricio</juez>
    </partido>


</liga>
