=== KerinR432/PaginasWebs/introducción-xml/rugby.dtd
<!ELEMENT temporadas (jornadas?)>
<!ATTLIST temporadas
anyo CDATA #REQUIRED>
<!ELEMENT jornadas (partidos*)>
<!ELEMENT Inglaterra EMPTY>
<!ATTLIST Inglaterra
es (local|visitante) #REQUIRED>
<!ELEMENT Francia EMPTY>
<!ATTLIST Francia
es (local|visitante) #REQUIRED>
<!ELEMENT Irlanda EMPTY>
<!ATTLIST Irlanda
es (local|visitante) #REQUIRED>
<!ELEMENT Escocia EMPTY>
<!ATTLIST Escocia
es (local|visitante) #REQUIRED>
<!ELEMENT Gales EMPTY>
<!ATTLIST Gales
es (local|visitante) #REQUIRED>
<!ELEMENT Italia EMPTY>
<!ATTLIST Italia
es (local|visitante) #REQUIRED>
<!ELEMENT partidos ((Inglaterra|Francia|Irlanda|Escocia|Gales|Italia)*,jugando?,resultados?,desplazamiento?)>
<!ATTLIST partidos
 orden ID #REQUIRED>
<!ELEMENT resultados (resultado,fecha,estadio,aforo)>
<!ELEMENT jugando ((Inglaterra|Francia|Irlanda|Escocia|Gales|Italia)*)>
<!ELEMENT desplazamiento (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT estadio (#PCDATA)>
<!ELEMENT aforo (#PCDATA)>

=== KerinR432/PaginasWebs/introducción-xml/rugby.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporadas SYSTEM "rugby.dtd">
<temporadas anyo="2024">
    <jornadas>
        <partidos orden = "P1">
        <Inglaterra es ="visitante"></Inglaterra>
        <Francia es="local"></Francia>
        <Irlanda es="visitante"></Irlanda>
        <Escocia es="visitante"></Escocia>
        <Gales es="visitante"></Gales>
        <Italia es="visitante"></Italia>
        <jugando>
            <Irlanda es="visitante"></Irlanda>
            <Francia es="local"></Francia>
        </jugando>
            <resultados>
                <resultado>
                    1 equipo local, 5 visitantes
                    victoria visitante 55 - 10
                </resultado>
                <fecha>
                    27-2-2024
                </fecha>
                <estadio>
                    Aviva Stadium
                </estadio>
                <aforo>
                    16000
                </aforo>
            </resultados>
        </partidos>

        <partidos orden = "P2">
        <Inglaterra es ="local"></Inglaterra>
        <Francia es="visitante"></Francia>
        <Irlanda es="visitante"></Irlanda>
        <Escocia es="visitante"></Escocia>
        <Gales es="visitante"></Gales>
        <Italia es="visitante"></Italia>
         <jugando>
            <Inglaterra es="local"></Inglaterra>
            <Francia es="visitante"></Francia>
        </jugando>
            <resultados>
                <resultado>
                    1 equipo local, 1 visitantes
                    victoria local 12-0
                </resultado>
                <fecha>
                    24-2-2024
                </fecha>
                <estadio>
                    Twickenham
                </estadio>
                <aforo>
                    49000
                </aforo>
            </resultados>
        </partidos>


        <partidos orden = "P3">
        <Inglaterra es ="visitante"></Inglaterra>
        <Francia es="visitante"></Francia>
        <Irlanda es="visitante"></Irlanda>
        <Escocia es="visitante"></Escocia>
        <Gales es="visitante"></Gales>
        <Italia es="local"></Italia>
            <desplazamiento>
                lluvias intensas
            </desplazamiento>
        </partidos>       
    </jornadas>
</temporadas>
