=== KerinR432/PaginasWebs/introducción-xml/xml/biblioteca.dtd
<!ELEMENT biblioteca (libro+,usuario*,prestamo*)>
<!ELEMENT libro (isbn,titulo,autor+)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT usuario (nombre,apellido,apellido?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT prestamo (fechaIni,fechaFin)>
<!ELEMENT fechaIni (#PCDATA)>
<!ELEMENT fechaFin (#PCDATA)>

<!ATTLIST libro
    cod ID #REQUIRED
>
<!ATTLIST usuario
    matricula ID #REQUIRED
>
<!ATTLIST prestamo
    libro IDREF #REQUIRED
    usuario IDREF #REQUIRED
>

=== KerinR432/PaginasWebs/introducción-xml/biblioteca.xml
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libro cod = "M1">
        <isbn>987876</isbn>
        <titulo>el capitan greo</titulo>
        <autor>Alicia First</autor>
    </libro>
    <libro cod = "M2">
        <isbn>987875</isbn>
        <titulo>Mi oso y yo</titulo>
        <autor>Pepe PÃ³tamo</autor>
    </libro>
    <usuario matricula="L878">
        <nombre>Antonio</nombre>
        <apellido>Penna</apellido>
    </usuario>
    <prestamo libro="M1" usuario="L878">
        <fechaIni>03/03/2025</fechaIni>
        <fechaFin>18/03/2025</fechaFin>
    </prestamo>
</biblioteca>
